# Site settings
title: "2024 Fall CS582 Machine Learning for Bioinformatics"
description: "Course materials and notes for UIUC class CS582 ML for Bioinformatics"
baseurl: ""
url: "https://cs582mlb.github.io"
#url: "127.0.0.1"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
